// =============================================================================
// recovery_catalog.cpp — Implementation of RecoveryCatalog
//
// Two SQLite3 databases:
//   • embedded_recovery DB  → loaded via sqlite3_deserialize() from the C
//     array generated by tools/gen_recovery_db.py (embedded_recovery_db.cpp).
//     Opened in SQLITE_DESERIALIZE_READONLY so SQLite never touches the array.
//   • user_research.db      → plain file in the user's data directory.
//     Created on first run with minimal schema (observations, aliases).
//
// All public query methods are thin wrappers around a private "_locked"
// helper.  The global mutex m_mu is acquired for every DB operation, which is
// fine because: (a) the catalog is queried from the ImGui render thread which
// fires at most 60 Hz, and (b) all hot-path structs (≤17) fit in a future
// LRU cache if profiling ever shows them as a hotspot.
// =============================================================================

#include "game/research/recovery_catalog.h"
#include <sqlite3.h>
#include <cstring>
#include <iostream>
#include <sstream>
#include <filesystem>

namespace swordfare::research {

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------
RecoveryCatalog& RecoveryCatalog::instance() {
    static RecoveryCatalog s_instance;
    return s_instance;
}

// ---------------------------------------------------------------------------
// RAII helper: auto-finalise a prepared statement
// ---------------------------------------------------------------------------
struct StmtGuard {
    sqlite3_stmt* s = nullptr;
    ~StmtGuard() { if (s) sqlite3_finalize(s); }
};

// ---------------------------------------------------------------------------
// Internal utilities
// ---------------------------------------------------------------------------
static const char* col_text(sqlite3_stmt* s, int col) {
    const char* v = reinterpret_cast<const char*>(sqlite3_column_text(s, col));
    return v ? v : "";
}

// NULL-safe integer column read.  Several embedded columns are nullable
// (offset_arm32, size_arm32, vtable_rva, target_func_rva); sqlite3_column_int
// returns 0 for NULL, but being explicit keeps the intent obvious.
static int col_int_or(sqlite3_stmt* s, int col, int fallback = 0) {
    if (sqlite3_column_type(s, col) == SQLITE_NULL) return fallback;
    return sqlite3_column_int(s, col);
}

static std::string trim_copy(const std::string& in) {
    size_t b = in.find_first_not_of(" \t\r\n");
    if (b == std::string::npos) return {};
    size_t e = in.find_last_not_of(" \t\r\n");
    return in.substr(b, e - b + 1);
}

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------
void RecoveryCatalog::init(const std::string& user_data_dir) {
    std::lock_guard<std::mutex> lg(m_mu);
    if (m_ready) return;

    if (!open_embedded_db()) {
        std::cerr << "[RecoveryCatalog] Failed to open embedded recovery DB\n";
        return;
    }

    std::string upath = user_data_dir + "/user_research.db";
    m_user_db_path = upath;
    if (!open_user_db(upath)) {
        std::cerr << "[RecoveryCatalog] Failed to open user research DB at " << upath << "\n";
        // Non-fatal: we can still read from the embedded DB.
    } else {
        ensure_user_schema();
    }

    m_ready = true;
    std::cout << "[RecoveryCatalog] Ready. Embedded DB: "
              << embedded_recovery_db_size() << " bytes in binary.\n";
}

void RecoveryCatalog::shutdown() {
    std::lock_guard<std::mutex> lg(m_mu);
    if (m_embedded) { sqlite3_close(m_embedded); m_embedded = nullptr; }
    if (m_user)     { sqlite3_close(m_user);     m_user     = nullptr; }
    m_ready = false;
}

bool RecoveryCatalog::is_ready() const {
    std::lock_guard<std::mutex> lg(m_mu);
    return m_ready;
}

// ---------------------------------------------------------------------------
// open_embedded_db — deserialize compiled-in bytes into an in-memory DB
// ---------------------------------------------------------------------------
bool RecoveryCatalog::open_embedded_db() {
    int rc = sqlite3_open(":memory:", &m_embedded);
    if (rc != SQLITE_OK) {
        std::cerr << "[RecoveryCatalog] sqlite3_open(:memory:) failed: "
                  << sqlite3_errmsg(m_embedded) << "\n";
        return false;
    }

    // sqlite3_deserialize copies/manages the buffer internally.
    // SQLITE_DESERIALIZE_FREEONCLOSE tells SQLite to free the buffer it owns;
    // SQLITE_DESERIALIZE_RESIZEABLE allows it to grow if needed for queries.
    // We provide a READ-ONLY copy so we pass neither — SQLite gets a
    // malloc'd copy of our const array.
    const size_t db_size = embedded_recovery_db_size();
    unsigned char* buf = static_cast<unsigned char*>(sqlite3_malloc64(db_size));
    if (!buf) {
        std::cerr << "[RecoveryCatalog] sqlite3_malloc64(" << db_size << ") failed\n";
        return false;
    }
    std::memcpy(buf, embedded_recovery_db_data(), db_size);

    rc = sqlite3_deserialize(
        m_embedded,
        "main",
        buf,
        static_cast<sqlite3_int64>(db_size),
        static_cast<sqlite3_int64>(db_size),
        SQLITE_DESERIALIZE_FREEONCLOSE   // SQLite frees buf on close
    );
    if (rc != SQLITE_OK) {
        std::cerr << "[RecoveryCatalog] sqlite3_deserialize failed: "
                  << sqlite3_errmsg(m_embedded) << "\n";
        sqlite3_free(buf);
        return false;
    }
    // Prevent any writes to the embedded DB.
    sqlite3_exec(m_embedded, "PRAGMA query_only = ON;", nullptr, nullptr, nullptr);
    return true;
}

// ---------------------------------------------------------------------------
// open_user_db
// ---------------------------------------------------------------------------
bool RecoveryCatalog::open_user_db(const std::string& path) {
    // Ensure the directory exists
    std::error_code ec;
    std::filesystem::create_directories(
        std::filesystem::path(path).parent_path(), ec);

    int rc = sqlite3_open(path.c_str(), &m_user);
    if (rc != SQLITE_OK) {
        std::cerr << "[RecoveryCatalog] sqlite3_open(" << path << ") failed: "
                  << sqlite3_errmsg(m_user) << "\n";
        return false;
    }
    sqlite3_exec(m_user, "PRAGMA journal_mode=WAL;", nullptr, nullptr, nullptr);
    sqlite3_exec(m_user, "PRAGMA synchronous=NORMAL;", nullptr, nullptr, nullptr);
    return true;
}

// ---------------------------------------------------------------------------
// ensure_user_schema — create tables if they don't exist
// ---------------------------------------------------------------------------
bool RecoveryCatalog::ensure_user_schema() {
    const char* sql = R"(
CREATE TABLE IF NOT EXISTS runtime_observations (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    struct_name TEXT NOT NULL,
    guest_va    INTEGER NOT NULL,
    note        TEXT,
    observed_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS field_aliases (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    struct_id   INTEGER NOT NULL,
    offset_arm64 INTEGER NOT NULL,
    alias_name  TEXT NOT NULL,
    note        TEXT,
    created_at  TEXT DEFAULT (datetime('now')),
    UNIQUE(struct_id, offset_arm64)
);
CREATE INDEX IF NOT EXISTS idx_obs_struct ON runtime_observations(struct_name);
CREATE INDEX IF NOT EXISTS idx_alias_struct ON field_aliases(struct_id);
)";
    char* errmsg = nullptr;
    int rc = sqlite3_exec(m_user, sql, nullptr, nullptr, &errmsg);
    if (rc != SQLITE_OK) {
        std::cerr << "[RecoveryCatalog] ensure_user_schema failed: " << errmsg << "\n";
        sqlite3_free(errmsg);
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// _build_struct_index_locked / _id_for_key_locked / _key_for_id_locked
//
// The embedded DB keys `structs` by a TEXT id (struct_id = "Scene"), while the
// public API exposes dense int ids.  The mapping is: int id == position of the
// row in `structs ORDER BY name` — the exact order all_structs() returns — so
// ids stay stable for the process lifetime and every int-keyed query can be
// resolved back to its TEXT key before hitting SQLite.
// ---------------------------------------------------------------------------
void RecoveryCatalog::_build_struct_index_locked() const {
    if (m_struct_index_built || !m_embedded) return;
    m_struct_index_built = true;   // one attempt; never retried per call
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, "SELECT struct_id FROM structs ORDER BY name;",
                           -1, &g.s, nullptr) != SQLITE_OK)
        return;
    while (sqlite3_step(g.s) == SQLITE_ROW) {
        std::string key = col_text(g.s, 0);
        int id = static_cast<int>(m_struct_key_by_id.size());
        m_struct_key_by_id.push_back(key);   // keep ids dense even if key empty
        if (!key.empty()) m_struct_id_by_key.emplace(std::move(key), id);
    }
}

std::optional<int>
RecoveryCatalog::_id_for_key_locked(const std::string& key) const {
    if (key.empty()) return std::nullopt;
    _build_struct_index_locked();
    auto it = m_struct_id_by_key.find(key);
    if (it == m_struct_id_by_key.end()) return std::nullopt;
    return it->second;
}

const std::string*
RecoveryCatalog::_key_for_id_locked(int id) const {
    _build_struct_index_locked();
    if (id < 0 || id >= static_cast<int>(m_struct_key_by_id.size())) return nullptr;
    return &m_struct_key_by_id[static_cast<size_t>(id)];
}

// ---------------------------------------------------------------------------
// Row readers — the embedded `structs` row is
//   (struct_id, build_id, name, size_arm64, summary)
// and source provenance lives in `recovery_sources`.
// ---------------------------------------------------------------------------
static std::string struct_source_citation(sqlite3* db, const std::string& key) {
    StmtGuard g;
    if (sqlite3_prepare_v2(db,
            "SELECT citation FROM recovery_sources WHERE target_id = ? "
            "ORDER BY source_id LIMIT 1;", -1, &g.s, nullptr) != SQLITE_OK)
        return {};
    sqlite3_bind_text(g.s, 1, key.c_str(), -1, SQLITE_TRANSIENT);
    if (sqlite3_step(g.s) != SQLITE_ROW) return {};
    return col_text(g.s, 0);
}

static CatalogStruct read_struct_row(sqlite3* db, sqlite3_stmt* s) {
    CatalogStruct cs;
    cs.key         = col_text(s, 0);                            // struct_id
    cs.build       = col_text(s, 1);                            // build_id
    cs.name        = col_text(s, 2);                            // name
    cs.size_bytes  = static_cast<uint32_t>(col_int_or(s, 3));   // size_arm64
    cs.notes       = col_text(s, 4);                            // summary
    cs.source_file = struct_source_citation(db, cs.key);
    return cs;
}

static constexpr const char* kStructSelect =
    "SELECT struct_id, build_id, name, size_arm64, summary FROM structs ";

// ---------------------------------------------------------------------------
// _find_struct_locked (must be called with m_mu held)
// ---------------------------------------------------------------------------
std::optional<CatalogStruct>
RecoveryCatalog::_find_struct_locked(const std::string& name) const {
    if (!m_embedded) return std::nullopt;
    std::string sql = std::string(kStructSelect) + "WHERE name = ? LIMIT 1;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql.c_str(), -1, &g.s, nullptr) != SQLITE_OK)
        return std::nullopt;
    sqlite3_bind_text(g.s, 1, name.c_str(), -1, SQLITE_TRANSIENT);
    if (sqlite3_step(g.s) != SQLITE_ROW) return std::nullopt;
    CatalogStruct cs = read_struct_row(m_embedded, g.s);
    if (auto id = _id_for_key_locked(cs.key)) cs.id = *id;
    return cs;
}

// ---------------------------------------------------------------------------
// Public struct queries
// ---------------------------------------------------------------------------
std::optional<CatalogStruct>
RecoveryCatalog::find_struct(const std::string& name) const {
    std::lock_guard<std::mutex> lg(m_mu);
    return _find_struct_locked(name);
}

std::optional<CatalogStruct>
RecoveryCatalog::find_struct_by_id(int id) const {
    std::lock_guard<std::mutex> lg(m_mu);
    if (!m_embedded) return std::nullopt;
    const std::string* key = _key_for_id_locked(id);
    if (!key) return std::nullopt;
    std::string sql = std::string(kStructSelect) + "WHERE struct_id = ? LIMIT 1;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql.c_str(), -1, &g.s, nullptr) != SQLITE_OK)
        return std::nullopt;
    sqlite3_bind_text(g.s, 1, key->c_str(), -1, SQLITE_TRANSIENT);
    if (sqlite3_step(g.s) != SQLITE_ROW) return std::nullopt;
    CatalogStruct cs = read_struct_row(m_embedded, g.s);
    cs.id = id;
    return cs;
}

std::vector<CatalogStruct> RecoveryCatalog::all_structs() const {
    std::lock_guard<std::mutex> lg(m_mu);
    std::vector<CatalogStruct> out;
    if (!m_embedded) return out;
    // ORDER BY name — must match _build_struct_index_locked() so that the id
    // assigned here is the same id the index resolves back to a TEXT key.
    std::string sql = std::string(kStructSelect) + "ORDER BY name;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql.c_str(), -1, &g.s, nullptr) != SQLITE_OK)
        return out;
    int next_id = 0;
    while (sqlite3_step(g.s) == SQLITE_ROW) {
        CatalogStruct cs = read_struct_row(m_embedded, g.s);
        cs.id = next_id++;
        out.push_back(std::move(cs));
    }
    return out;
}

// ---------------------------------------------------------------------------
// _fields_locked (must be called with m_mu held)
// ---------------------------------------------------------------------------
std::vector<CatalogField>
RecoveryCatalog::_fields_locked(int struct_id) const {
    std::vector<CatalogField> out;
    if (!m_embedded) return out;
    const std::string* key = _key_for_id_locked(struct_id);
    if (!key) return out;
    // struct_fields: (field_id, struct_id, offset_arm64, offset_arm32, size,
    //                 type_name, canonical_name, is_embedded, confidence,
    //                 unsafe_raw, note)
    const char* sql =
        "SELECT offset_arm64, offset_arm32, size, type_name, canonical_name, "
        "       confidence, note "
        "FROM struct_fields WHERE struct_id = ? ORDER BY offset_arm64;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql, -1, &g.s, nullptr) != SQLITE_OK)
        return out;
    sqlite3_bind_text(g.s, 1, key->c_str(), -1, SQLITE_TRANSIENT);
    int row = 0;
    while (sqlite3_step(g.s) == SQLITE_ROW) {
        CatalogField f;
        f.id           = row++;                        // field_id is TEXT in the DB
        f.struct_id    = struct_id;
        f.offset_arm64 = static_cast<uint32_t>(col_int_or(g.s, 0));
        f.offset_arm32 = static_cast<uint32_t>(col_int_or(g.s, 1));
        f.size_bytes   = static_cast<uint32_t>(col_int_or(g.s, 2));
        f.field_type   = col_text(g.s, 3);             // type_name
        f.field_name   = col_text(g.s, 4);             // canonical_name
        f.confidence   = col_text(g.s, 5);
        f.notes        = col_text(g.s, 6);
        out.push_back(std::move(f));
    }
    return out;
}

std::vector<CatalogField>
RecoveryCatalog::fields_for_struct(int struct_id) const {
    std::lock_guard<std::mutex> lg(m_mu);
    return _fields_locked(struct_id);
}

std::optional<uint32_t>
RecoveryCatalog::field_offset64(const std::string& struct_name,
                                const std::string& field_name) const {
    std::lock_guard<std::mutex> lg(m_mu);
    auto s = _find_struct_locked(struct_name);
    if (!s) return std::nullopt;
    auto fields = _fields_locked(s->id);
    for (auto& f : fields)
        if (f.field_name == field_name) return f.offset_arm64;
    return std::nullopt;
}

std::optional<uint32_t>
RecoveryCatalog::field_offset32(const std::string& struct_name,
                                const std::string& field_name) const {
    std::lock_guard<std::mutex> lg(m_mu);
    auto s = _find_struct_locked(struct_name);
    if (!s) return std::nullopt;
    auto fields = _fields_locked(s->id);
    for (auto& f : fields)
        if (f.field_name == field_name) return f.offset_arm32;
    return std::nullopt;
}

// ---------------------------------------------------------------------------
// _vtable_locked
// ---------------------------------------------------------------------------
std::optional<CatalogVtable>
RecoveryCatalog::_vtable_locked(int struct_id, bool include_slots) const {
    if (!m_embedded) return std::nullopt;
    const std::string* key = _key_for_id_locked(struct_id);
    if (!key) return std::nullopt;
    // vtables: (vtable_id, struct_id, vtable_rva, interface_name, slot_count)
    // NOTE: vtable_rva is a module-relative offset (e.g. 0x62A5E8), not a VA.
    const char* sql =
        "SELECT vtable_id, vtable_rva, interface_name, slot_count "
        "FROM vtables WHERE struct_id = ? LIMIT 1;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql, -1, &g.s, nullptr) != SQLITE_OK)
        return std::nullopt;
    sqlite3_bind_text(g.s, 1, key->c_str(), -1, SQLITE_TRANSIENT);
    if (sqlite3_step(g.s) != SQLITE_ROW) return std::nullopt;

    std::string vtable_key = col_text(g.s, 0);
    CatalogVtable vt;
    vt.id         = 0;                                  // vtable_id is TEXT in the DB
    vt.struct_id  = struct_id;
    vt.vptr_arm64 = static_cast<uint64_t>(col_int_or(g.s, 1));
    vt.vptr_arm32 = 0;                                  // no arm32 column in the DB
    vt.slot_count = col_int_or(g.s, 3);
    vt.notes      = col_text(g.s, 2);                   // interface_name

    if (include_slots && !vtable_key.empty()) {
        // vtable_slots: (vtable_id, slot_index, slot_offset, target_func_rva,
        //                demangled_name)
        const char* ssql =
            "SELECT slot_index, slot_offset, target_func_rva, demangled_name "
            "FROM vtable_slots WHERE vtable_id = ? ORDER BY slot_index;";
        StmtGuard gs;
        if (sqlite3_prepare_v2(m_embedded, ssql, -1, &gs.s, nullptr) == SQLITE_OK) {
            sqlite3_bind_text(gs.s, 1, vtable_key.c_str(), -1, SQLITE_TRANSIENT);
            while (sqlite3_step(gs.s) == SQLITE_ROW) {
                CatalogVtableSlot sl;
                sl.id          = col_int_or(gs.s, 0);
                sl.vtable_id   = 0;
                sl.slot_index  = col_int_or(gs.s, 0);
                sl.vaddr_arm64 = static_cast<uint64_t>(col_int_or(gs.s, 2));
                sl.vaddr_arm32 = 0;
                sl.symbol_name = col_text(gs.s, 3);     // demangled_name
                char off[32];
                snprintf(off, sizeof(off), "+0x%X",
                         static_cast<unsigned>(col_int_or(gs.s, 1)));
                sl.notes = off;
                vt.slots.push_back(std::move(sl));
            }
        }
    }
    return vt;
}

std::optional<CatalogVtable>
RecoveryCatalog::vtable_for_struct(int struct_id, bool include_slots) const {
    std::lock_guard<std::mutex> lg(m_mu);
    return _vtable_locked(struct_id, include_slots);
}

std::optional<CatalogVtable>
RecoveryCatalog::vtable_by_vptr64(uint64_t vptr) const {
    std::lock_guard<std::mutex> lg(m_mu);
    if (!m_embedded) return std::nullopt;
    // vtable_rva holds a module-relative offset (the canonical form in the
    // embedded DB), so the lookup compares against the RVA space.
    const char* sql =
        "SELECT struct_id, vtable_rva, interface_name, slot_count "
        "FROM vtables WHERE vtable_rva = ? LIMIT 1;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql, -1, &g.s, nullptr) != SQLITE_OK)
        return std::nullopt;
    sqlite3_bind_int64(g.s, 1, static_cast<sqlite3_int64>(vptr));
    if (sqlite3_step(g.s) != SQLITE_ROW) return std::nullopt;
    CatalogVtable vt;
    std::string skey = col_text(g.s, 0);
    if (auto id = _id_for_key_locked(skey)) vt.struct_id = *id;
    vt.vptr_arm64 = static_cast<uint64_t>(col_int_or(g.s, 1));
    vt.slot_count = col_int_or(g.s, 3);
    vt.notes      = col_text(g.s, 2);
    return vt;
}

// ---------------------------------------------------------------------------
// Proto fields
// ---------------------------------------------------------------------------
std::vector<CatalogProtoField>
RecoveryCatalog::proto_fields_for_struct(int struct_id) const {
    std::lock_guard<std::mutex> lg(m_mu);
    std::vector<CatalogProtoField> out;
    if (!m_embedded) return out;
    const std::string* key = _key_for_id_locked(struct_id);
    if (!key) return out;
    // proto_fields: (struct_id, field_offset_arm64, proto_number, proto_type)
    // proto_type is a human string such as "int32 (current_health)".
    const char* sql =
        "SELECT field_offset_arm64, proto_number, proto_type "
        "FROM proto_fields WHERE struct_id = ? ORDER BY proto_number;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql, -1, &g.s, nullptr) != SQLITE_OK)
        return out;
    sqlite3_bind_text(g.s, 1, key->c_str(), -1, SQLITE_TRANSIENT);
    while (sqlite3_step(g.s) == SQLITE_ROW) {
        CatalogProtoField pf;
        pf.struct_id  = struct_id;
        pf.tag        = col_int_or(g.s, 1);
        pf.id         = pf.tag;

        const uint32_t off = static_cast<uint32_t>(col_int_or(g.s, 0));
        const std::string raw = col_text(g.s, 2);
        // Split "int32 (current_health)" into type + descriptive name.
        std::string type_tok = raw, name_tok;
        if (size_t lp = raw.find('('); lp != std::string::npos) {
            type_tok = trim_copy(raw.substr(0, lp));
            size_t rp = raw.find(')', lp + 1);
            name_tok = trim_copy(raw.substr(lp + 1,
                                            (rp == std::string::npos ? raw.size() : rp)
                                                - lp - 1));
        }
        if (type_tok == "int32" || type_tok == "int64" || type_tok == "uint32" ||
            type_tok == "uint64" || type_tok == "sint32" || type_tok == "sint64" ||
            type_tok == "bool" || type_tok == "enum")
            pf.wire_type = "varint";
        else if (type_tok == "float" || type_tok == "fixed32" || type_tok == "sfixed32")
            pf.wire_type = "fixed32";
        else if (type_tok == "double" || type_tok == "fixed64" || type_tok == "sfixed64")
            pf.wire_type = "fixed64";
        else if (type_tok == "string" || type_tok == "bytes" || type_tok == "message")
            pf.wire_type = "length_delimited";

        pf.cpp_field  = name_tok.empty() ? type_tok : name_tok;
        pf.proto_name = raw;
        char nt[48];
        snprintf(nt, sizeof(nt), "field offset +0x%X", off);
        pf.notes = nt;
        out.push_back(std::move(pf));
    }
    return out;
}

// ---------------------------------------------------------------------------
// Relationships
// ---------------------------------------------------------------------------
// relationships: (from_struct_id, offset_arm64, to_struct_id, rel_kind,
//                 container_elem_type) — both struct columns hold TEXT ids,
// which in this DB are the struct *names*, so they double as the display names.
std::vector<CatalogRelationship>
RecoveryCatalog::_relationships_locked(int struct_id, bool from_side) const {
    std::vector<CatalogRelationship> out;
    if (!m_embedded) return out;
    const std::string* key = _key_for_id_locked(struct_id);
    if (!key) return out;
    std::string sql =
        "SELECT from_struct_id, offset_arm64, to_struct_id, rel_kind, "
        "       container_elem_type FROM relationships WHERE ";
    sql += from_side ? "from_struct_id" : "to_struct_id";
    sql += " = ? ORDER BY offset_arm64;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_embedded, sql.c_str(), -1, &g.s, nullptr) != SQLITE_OK)
        return out;
    sqlite3_bind_text(g.s, 1, key->c_str(), -1, SQLITE_TRANSIENT);
    int row = 0;
    while (sqlite3_step(g.s) == SQLITE_ROW) {
        CatalogRelationship r;
        r.id           = row++;
        r.from_name    = col_text(g.s, 0);
        r.to_name      = col_text(g.s, 2);
        if (auto fid = _id_for_key_locked(r.from_name)) r.from_id = *fid;
        if (auto tid = _id_for_key_locked(r.to_name))   r.to_id   = *tid;
        r.offset_arm64 = static_cast<uint32_t>(col_int_or(g.s, 1));
        r.kind         = col_text(g.s, 3);          // rel_kind
        r.notes        = col_text(g.s, 4);          // container_elem_type
        out.push_back(std::move(r));
    }
    return out;
}

std::vector<CatalogRelationship>
RecoveryCatalog::relationships_from(int struct_id) const {
    std::lock_guard<std::mutex> lg(m_mu);
    return _relationships_locked(struct_id, true);
}

std::vector<CatalogRelationship>
RecoveryCatalog::relationships_to(int struct_id) const {
    std::lock_guard<std::mutex> lg(m_mu);
    return _relationships_locked(struct_id, false);
}

// ---------------------------------------------------------------------------
// User research DB writes
// ---------------------------------------------------------------------------
void RecoveryCatalog::record_runtime_observation(const std::string& struct_name,
                                                  uint64_t           guest_va,
                                                  const std::string& note) {
    std::lock_guard<std::mutex> lg(m_mu);
    if (!m_user) return;
    const char* sql =
        "INSERT INTO runtime_observations(struct_name, guest_va, note) VALUES(?,?,?);";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_user, sql, -1, &g.s, nullptr) != SQLITE_OK) return;
    sqlite3_bind_text(g.s, 1, struct_name.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_int64(g.s, 2, static_cast<sqlite3_int64>(guest_va));
    sqlite3_bind_text(g.s, 3, note.c_str(), -1, SQLITE_STATIC);
    sqlite3_step(g.s);
}

void RecoveryCatalog::set_field_alias(int struct_id, uint32_t offset_arm64,
                                       const std::string& alias_name,
                                       const std::string& note) {
    std::lock_guard<std::mutex> lg(m_mu);
    if (!m_user) return;
    const char* sql =
        "INSERT INTO field_aliases(struct_id, offset_arm64, alias_name, note) "
        "VALUES(?,?,?,?) "
        "ON CONFLICT(struct_id, offset_arm64) DO UPDATE SET alias_name=excluded.alias_name, note=excluded.note;";
    StmtGuard g;
    if (sqlite3_prepare_v2(m_user, sql, -1, &g.s, nullptr) != SQLITE_OK) return;
    sqlite3_bind_int(g.s, 1, struct_id);
    sqlite3_bind_int(g.s, 2, static_cast<int>(offset_arm64));
    sqlite3_bind_text(g.s, 3, alias_name.c_str(), -1, SQLITE_STATIC);
    sqlite3_bind_text(g.s, 4, note.c_str(), -1, SQLITE_STATIC);
    sqlite3_step(g.s);
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------
std::string RecoveryCatalog::status_summary() const {
    std::lock_guard<std::mutex> lg(m_mu);
    std::ostringstream ss;
    if (!m_ready) { ss << "Not initialised"; return ss.str(); }
    // Count structs
    int nstructs = 0;
    {
        StmtGuard g;
        if (sqlite3_prepare_v2(m_embedded,
                "SELECT COUNT(*) FROM structs;", -1, &g.s, nullptr) == SQLITE_OK &&
            sqlite3_step(g.s) == SQLITE_ROW)
            nstructs = sqlite3_column_int(g.s, 0);
    }
    int nfields = 0;
    {
        StmtGuard g;
        if (sqlite3_prepare_v2(m_embedded,
                "SELECT COUNT(*) FROM struct_fields;", -1, &g.s, nullptr) == SQLITE_OK &&
            sqlite3_step(g.s) == SQLITE_ROW)
            nfields = sqlite3_column_int(g.s, 0);
    }
    ss << "Embedded DB: " << (embedded_recovery_db_size() / 1024) << " KB  |  "
       << nstructs << " structs  " << nfields << " fields";
    if (m_user)
        ss << "\nUser DB: " << m_user_db_path;
    return ss.str();
}

std::vector<RecoveryCatalog::TableStat> RecoveryCatalog::table_stats() const {
    std::lock_guard<std::mutex> lg(m_mu);
    std::vector<TableStat> out;
    if (!m_embedded) return out;
    const char* tables[] = {
        "builds", "modules", "structs", "struct_fields",
        "vtables", "vtable_slots", "proto_fields", "relationships",
        "recovery_sources", nullptr
    };
    for (int i = 0; tables[i]; ++i) {
        char sql[128];
        snprintf(sql, sizeof(sql), "SELECT COUNT(*) FROM %s;", tables[i]);
        StmtGuard g;
        TableStat ts;
        ts.name = tables[i];
        if (sqlite3_prepare_v2(m_embedded, sql, -1, &g.s, nullptr) == SQLITE_OK &&
            sqlite3_step(g.s) == SQLITE_ROW)
            ts.row_count = sqlite3_column_int(g.s, 0);
        out.push_back(ts);
    }
    return out;
}

} // namespace swordfare::research
